version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    target-branch: "master"
