run:
  deadline: 5m

linters-settings:
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - goimports
    - golint
    - govet
    - misspell
    - errcheck
    - staticcheck
    - prealloc
    - ineffassign
    - unused
    - gocyclo
    - gosimple
    - structcheck
    - varcheck
    - maligned
