run:
  deadline: 5m

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - ineffassign

linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - misspell
    - errcheck
    - staticcheck
    - prealloc
    - ineffassign
    # - unused
    - gocyclo
    - gosimple
    - structcheck
    - varcheck
    - maligned
    - gosec
