version: 2.1

commands:
  lint:
    parameters:
      GOLANGCI_LINT_VERSION:
        type: string
        default: 1.21.0
    steps:
      - run:
          name: Lint by golangci-lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v<< parameters.GOLANGCI_LINT_VERSION >>
            golangci-lint run -v ./...
  test:
    steps:
      - run:
          name: test
          command: |
            go mod vendor
            go test -v ./...

jobs:
  test:
    docker:
      - image: golang:1.13
    environment:
      GO111MODULE: "on"
      GOSUMDB: "off"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-golang-playground-{{ checksum "go.sum" }}
      - lint
      - test
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: v1-golang-playground-{{ checksum "go.sum" }}

workflows:
    test:
      jobs:
        - test
